/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#755566",
        "primary-container": "#ad899b",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffd8ea",
        "primary-fixed-dim": "#e3bccf",
        secondary: "#6e595f",
        "secondary-container": "#f5d8e0",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#f8dbe2",
        "secondary-fixed-dim": "#dbc0c6",
        tertiary: "#615d60",
        "tertiary-container": "#979195",
        "on-tertiary": "#ffffff",
        background: "#fbf9f7",
        surface: "#fbf9f7",
        "surface-bright": "#fbf9f7",
        "surface-dim": "#dbdad8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f1",
        "surface-container": "#efedec",
        "surface-container-high": "#eae8e6",
        "surface-container-highest": "#e4e2e0",
        "on-background": "#1b1c1b",
        "on-surface": "#1b1c1b",
        "on-surface-variant": "#4e4448",
        outline: "#807479",
        "outline-variant": "#d1c3c8",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        gutter: "24px",
        "container-max": "1440px",
        unit: "8px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        sans: ["Hanken Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
}
